// <auto-generated />
using System;
using Crashguard.Engine.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Crashguard.Engine.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621130133_AddCheckpointsAndCompositeCanaryIndex")]
    partial class AddCheckpointsAndCompositeCanaryIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("Crashguard.Engine.Models.Canary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CanaryType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("canary_type");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reference_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_at");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("Timeout")
                        .HasColumnType("INTEGER")
                        .HasColumnName("timeout");

                    b.HasKey("Id")
                        .HasName("pk_canaries");

                    b.HasIndex("CanaryType", "ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("ix_canaries_canary_type_reference_id");

                    b.ToTable("canaries", (string)null);
                });

            modelBuilder.Entity("Crashguard.Engine.Models.CanaryCheckpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CanaryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("canary_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stage");

                    b.HasKey("Id")
                        .HasName("pk_canary_checkpoints");

                    b.HasIndex("CanaryId")
                        .HasDatabaseName("ix_canary_checkpoints_canary_id");

                    b.ToTable("canary_checkpoints", (string)null);
                });

            modelBuilder.Entity("Crashguard.Engine.Models.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("config");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_channels");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_channels_name");

                    b.ToTable("channels", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
