// <auto-generated />
using System;
using Crashguard.Engine.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Crashguard.Engine.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621145223_AddCanaryTypeDefaultChannels")]
    partial class AddCanaryTypeDefaultChannels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("Crashguard.Engine.Models.Canary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CanaryType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("canary_type");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reference_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_at");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("Timeout")
                        .HasColumnType("INTEGER")
                        .HasColumnName("timeout");

                    b.HasKey("Id")
                        .HasName("pk_canaries");

                    b.HasIndex("CanaryType", "ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("ix_canaries_canary_type_reference_id");

                    b.ToTable("canaries", (string)null);
                });

            modelBuilder.Entity("Crashguard.Engine.Models.CanaryCheckpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CanaryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("canary_id");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("stage");

                    b.HasKey("Id")
                        .HasName("pk_canary_checkpoints");

                    b.HasIndex("CanaryId")
                        .HasDatabaseName("ix_canary_checkpoints_canary_id");

                    b.ToTable("canary_checkpoints", (string)null);
                });

            modelBuilder.Entity("Crashguard.Engine.Models.CanaryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("MetadataSchema")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_schema");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("severity");

                    b.Property<int>("Timeout")
                        .HasColumnType("INTEGER")
                        .HasColumnName("timeout");

                    b.Property<string>("VerifierUrl")
                        .HasColumnType("TEXT")
                        .HasColumnName("verifier_url");

                    b.HasKey("Id")
                        .HasName("pk_canary_types");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_canary_types_name");

                    b.ToTable("canary_types", (string)null);
                });

            modelBuilder.Entity("Crashguard.Engine.Models.CanaryTypeChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CanaryTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("canary_type_id");

                    b.Property<int>("ChannelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("channel_id");

                    b.HasKey("Id")
                        .HasName("pk_canary_type_channels");

                    b.HasIndex("CanaryTypeId")
                        .HasDatabaseName("ix_canary_type_channels_canary_type_id");

                    b.HasIndex("ChannelId")
                        .HasDatabaseName("ix_canary_type_channels_channel_id");

                    b.HasIndex("CanaryTypeId", "ChannelId")
                        .IsUnique()
                        .HasDatabaseName("ix_canary_type_channels_canary_type_id_channel_id");

                    b.ToTable("canary_type_channels", (string)null);
                });

            modelBuilder.Entity("Crashguard.Engine.Models.CanaryTypeRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CanaryTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("canary_type_id");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("channel");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("field");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("operator");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("severity");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_canary_type_rules");

                    b.HasIndex("CanaryTypeId")
                        .HasDatabaseName("ix_canary_type_rules_canary_type_id");

                    b.ToTable("canary_type_rules", (string)null);
                });

            modelBuilder.Entity("Crashguard.Engine.Models.Channel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("config");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_channels");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_channels_name");

                    b.ToTable("channels", (string)null);
                });

            modelBuilder.Entity("Crashguard.Engine.Models.CanaryTypeChannel", b =>
                {
                    b.HasOne("Crashguard.Engine.Models.CanaryType", null)
                        .WithMany("DefaultChannels")
                        .HasForeignKey("CanaryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_canary_type_channels_canary_types_canary_type_id");

                    b.HasOne("Crashguard.Engine.Models.Channel", null)
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_canary_type_channels_channels_channel_id");
                });

            modelBuilder.Entity("Crashguard.Engine.Models.CanaryTypeRule", b =>
                {
                    b.HasOne("Crashguard.Engine.Models.CanaryType", null)
                        .WithMany("Rules")
                        .HasForeignKey("CanaryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_canary_type_rules_canary_types_canary_type_id");
                });

            modelBuilder.Entity("Crashguard.Engine.Models.CanaryType", b =>
                {
                    b.Navigation("DefaultChannels");

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
