// <auto-generated />
using System;
using Crashguard.Engine.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Crashguard.Engine.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260619162203_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("Crashguard.Engine.Models.Canary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("CanaryType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("canary_type");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at");

                    b.Property<string>("Metadata")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata");

                    b.Property<string>("ReferenceId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("reference_id");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_at");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("Timeout")
                        .HasColumnType("INTEGER")
                        .HasColumnName("timeout");

                    b.HasKey("Id")
                        .HasName("pk_canaries");

                    b.HasIndex("CanaryType")
                        .HasDatabaseName("ix_canaries_canary_type");

                    b.HasIndex("ReferenceId")
                        .IsUnique()
                        .HasDatabaseName("ix_canaries_reference_id");

                    b.ToTable("canaries", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
